SpaceSpectators/social_media_site/groups/urls.py
from django.urls import path
from . import views

app_name="groups"

urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
    path('group/<slug>/',views.MemberDetail.as_view(),name='group_member'),
    path('mygroups/<username>/',views.MyGroups.as_view(),name='mygroups'),

]

SpaceSpectators/social_media_site/posts/urls.py
from django.urls import path
from . import views

app_name="posts"

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('post/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
    path('post/<pk>/',views.add_comment_to_post,name='add_comment_post'),
    path('comment/<pk>/remove/',views.remove_comment,name='remove_comment'),
    path('group_post/<pk>/',views.add_post_from_group,name='group_posts')
]

SpaceSpectators/social_media_site/social_media_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include("accounts.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include("posts.urls")),
    path('groups/',include("groups.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SpaceSpectators/social_media_site/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from django.utils import timezone
# Create your models here.\
from django.contrib.auth import get_user_model
User=get_user_model()

class Post(models.Model):
    user=models.ForeignKey(User,related_name='posts',on_delete='CASCADE')
    created_date=models.DateTimeField(auto_now=True)
    message=models.TextField()
    message_html=models.TextField(editable=False)
    group=models.ForeignKey(Group,related_name='posts',on_delete=models.CASCADE,null=True,blank=True)
    photo=models.ImageField(upload_to='posts/images',blank=True,null=True)


    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering=['-created_date']
        unique_together=['user','message']

class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    author=models.ForeignKey(User,on_delete='CASCADE')
    text=models.TextField()
    create_date=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

SpaceSpectators/social_media_site/posts/forms.py
from posts.models import Comment,Post
from django import forms

class CommentForm(forms.ModelForm):

    class Meta():
        model=Comment
        fields=('text',)

class GroupPostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=('message','photo')

SpaceSpectators/social_media_site/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth.decorators import login_required
from groups.models import Group

# pip install django-braces
from braces.views import SelectRelatedMixin

from posts import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group','photo')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

@login_required
def add_post_from_group(request,pk):
    group=get_object_or_404(Group,pk=pk)
    if request.method=="POST":
        form=forms.GroupPostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.group=group
            post.save()
            return redirect('groups:single',slug=group.slug)

    else:
        form=forms.GroupPostForm()
        return render(request,'posts/group_post_form.html',{'form':form})

@login_required
def add_comment_to_post(request,pk):
    post=get_object_or_404(models.Post,pk=pk)
    if request.method=="POST":
        form=forms.CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.author=request.user
            comment.save()
            return redirect('posts:all')

    else:
        form=forms.CommentForm()
        return render(request,'posts/comment_form.html',{'form':form})


@login_required
def remove_comment(request,pk):
    comment=get_object_or_404(models.Comment,pk=pk)
    comment.delete()
    return redirect('posts:all')

SpaceSpectators/social_media_site/posts/templates/posts/_post.html
<div class="media">
	<div class="media-body">
    <div class="post">
    {% if post.photo %}
    <img width=600 height=400 src="{{post.photo.url}}" alt=""/>
    {% endif %}
		<h5>{{ post.message }}</h5>
    <span><h5 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h5></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_date }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a>{{ post.group.name }}</a></span>
			{% endif %}

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete Post</span>
				</a>
			{% endif %}
		</div>
      <a class='btn btn-warning btn-comment' href="{% url 'posts:add_comment_post' pk=post.pk %}">Add Comment</a>
  </div>
      {% for comment in post.comments.all %}
        <br>
        {% if user.is_authenticated %}
        <div class="comment">
        <p>{{comment.text|safe|linebreaks}}</p>
        <span>Posted By: @{{comment.author.username}} <span>
        <span>{{comment.create_date}}</span>
        {% if comment.author == user %}
        <span><a href="{% url 'posts:remove_comment' pk=comment.pk %}">Delete</a></span>
        {% endif %}
        </div>
        {% endif %}
        {% empty %}
        <p>No comments</p>
        {% endfor %}
    </div>
</div>

SpaceSpectators/social_media_site/posts/templates/posts/comment_form.html
{% extends "posts/post_base.html" %}
{% block content %}
{% load bootstrap4 %}
<h1>New comment</h1>
<form class="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary" value="Post Comment"></input>
</form>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/group_post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_content %}
<h3>Create New Post</h3>
<div class="container">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Create" class="btn btn-primary btn-lg">
  </form>
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/post_base.html
{% extends "base.html" %}
{% block content  %}
<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block after_post %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>
<div class="container">
  {% if post.photo %}
  <img width=600 height=400 src="{{post.photo.url}}" alt=""/>
  {% endif %}
</div>
<div class="">
  {{post.message}}  
</div>
<div class="delete">
  <form  method="post">
    {% csrf_token %}
    <input type="submit" name="" value="Delete" class="btn btn-danger btn-lg">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-secondary btn-lg">Cancel</a>
  </form>
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="col-md-8">
  {% include "posts/_post.html" %}
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_content %}
<h3>Create New Post</h3>
<div class="container">
  <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Create" class="btn btn-primary btn-lg">
  </form>
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<!-- <div class="col-md-4"> -->
  <!-- {% if user.is_authenticated %}
    <div class="">
      <div class="content">
          <h5>Your Groups</h5>
          <ul>
            {% for member_group in user_groups.all %}
				        <li class="group li-with-bullet">
					            <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				        </li>
				    {% endfor %}
          </ul>
      </div>
    </div>
    {% endif %}
    <div class="">
      <div class="content">
          <h5>All Groups</h5>
          <ul>
            {% for other_group in get_other_groups %}
              <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.group.slug}">{{other_group.group.name}}</a></li>
            {% endfor %}
          </ul>
      </div>
    </div> -->
<!-- </div> -->
{% endblock %}

{% block post_content %}


<div class="col-md-8">
  <h1>Your Space Wall</h1>
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>
{% endblock %}

SpaceSpectators/social_media_site/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}