SpaceSpectators/social_media_site/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="accounts"

urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')
]

SpaceSpectators/social_media_site/groups/urls.py
from django.urls import path
from . import views

app_name="groups"

urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
    path('group/<slug>/',views.MemberDetail.as_view(),name='group_member'),
    path('mygroups/<username>/',views.MyGroups.as_view(),name='mygroups'),

]

SpaceSpectators/social_media_site/posts/urls.py
from django.urls import path
from . import views

app_name="posts"

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('post/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
    path('post/<pk>/',views.add_comment_to_post,name='add_comment_post'),
    path('comment/<pk>/remove/',views.remove_comment,name='remove_comment'),
    path('group_post/<pk>/',views.add_post_from_group,name='group_posts')
]

SpaceSpectators/social_media_site/social_media_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include("accounts.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include("posts.urls")),
    path('groups/',include("groups.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SpaceSpectators/social_media_site/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Space Spectators</title>

    <link rel="stylesheet" href={% static "socialmedia/css/master.css" %}>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
   <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:all' %}">Space Spectators</a>
    <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:mygroups' username=user.username %}">My groups</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="container">
  {% block content %}
  {% endblock %}
</div>
<canvas id="canvas"></canvas>

   <!-- <script src="{% static "socialmedia/js/master.js"%}" type="text/javascript" ></script> -->

   <!-- Latest compiled and minified jQuery -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

SpaceSpectators/social_media_site/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
  <h1>Welcome to Space Spectators!</h1>
<img width=1200 height=600 align=left src="{% static "images/200799.jpg" %}">
{% endblock %}

SpaceSpectators/social_media_site/templates/test.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<h1>You are successfully logged in!</h1>

{% endblock %}

SpaceSpectators/social_media_site/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting come back soon!</h1>
{% endblock %}