SpaceSpectators/social_media_site/groups/urls.py
from django.urls import path
from . import views

app_name="groups"

urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
    path('group/<slug>/',views.MemberDetail.as_view(),name='group_member'),
    path('mygroups/<username>/',views.MyGroups.as_view(),name='mygroups'),

]

SpaceSpectators/social_media_site/posts/urls.py
from django.urls import path
from . import views

app_name="posts"

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('post/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
    path('post/<pk>/',views.add_comment_to_post,name='add_comment_post'),
    path('comment/<pk>/remove/',views.remove_comment,name='remove_comment'),
    path('group_post/<pk>/',views.add_post_from_group,name='group_posts')
]

SpaceSpectators/social_media_site/social_media_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include("accounts.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include("posts.urls")),
    path('groups/',include("groups.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SpaceSpectators/social_media_site/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

from django.contrib.auth import get_user_model
User=get_user_model()

from django import template
register=template.Library()


# Create your models here.

class Group(models.Model):
    name=models.CharField(max_length=256,unique=True)
    slug=models.SlugField(allow_unicode=True,unique=True)
    description=models.TextField(blank=True,default='')
    description_html=models.TextField(editable=False,default='')
    members=models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering=['name']

class GroupMember(models.Model):
    group=models.ForeignKey(Group,on_delete='CASCADE')
    user=models.ForeignKey(User,related_name='user_groups',on_delete='CASCADE')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together=('group','user')

SpaceSpectators/social_media_site/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from groups.models import Group,GroupMember
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields=('name','description')
    model=Group

class SingleGroup(generic.DetailView):
    model=Group


class ListGroups(generic.ListView):
    model=Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group=get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,'Warning already a memeber')

        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)

class MemberDetail(generic.DetailView):
    model=Group
    template_name='groups/group_member_detail.html'


class MyGroups(generic.ListView):
    model=GroupMember
    template_name='groups/mygroups.html'
    context_object_name='my_groups'




class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership=GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get('slug')).get()

        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group')

        else:
            membership.delete()
            messages.success(self.request,'You have left the group')

        return super().get(request,*args,**kwargs)

SpaceSpectators/social_media_site/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

SpaceSpectators/social_media_site/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="container">
<div class="group-content">
  <h1>{{group.name}}</h1>
  <h2>Member Count: {{group.members.count}}</h2>
  {% if user in group.members.all %}
  <a href="{% url 'posts:group_posts' pk=group.pk %}" class="btn btn-lg btn-primary"><span class="fa fa-plus"></span> Add Post</a>
  {% endif %}
  <a href="{% url 'groups:group_member' slug=group.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-user"></span> Members</a>
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-danger btn-lg"><span class="fa fa-times-circle-o"></span>Leave Group</a>
  {% else %}
  <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-danger btn-lg btn-primary"><span class="fa fa-check-circle-o"></span> Join Group</a>
  	{% endif %}
</div>
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h3>No posts in this group yet!</h3>
  {% else %}
  {% if user in group.members.all %}
  {% for post in group.posts.all %}
    {% include "posts/_post.html" %}
  {% endfor %}
  {% else %}
  <h3>Please join the group to view the posts</h3>
  {% endif %}
{% endif %}
</div>
{% endblock %}

SpaceSpectators/social_media_site/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
<h4>Create New Group</h4>
<div class="container">
  <form action="{% url 'groups:create' %}" method="post" id=groupForm>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Create" class="btn btn-primary btn-lg">
  </form>
</div>

{% endblock %}

SpaceSpectators/social_media_site/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! <br>Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'groups:single' slug=group.slug %}"
		class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description}}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
			<span></span><span></span>
			</div>
		</a>

		{% endfor %}
	</div>
</div>
{% endblock %}

SpaceSpectators/social_media_site/groups/templates/groups/group_member_detail.html
{% extends "groups/group_base.html" %}
{% block group_content %}
<h1>Members</h1>
<div class="container">
{% if group.members.count == 0 %}
<p>No members yet!</p>
{% endif %}
{% for g in group.members.all %}
  <ul>
    <h2><li class=""><a href="{% url 'posts:for_user' username=g.username %}">@{{g.username}}</a></li></h2>
  </ul>
{% endfor %}
</div>
{% endblock %}

SpaceSpectators/social_media_site/groups/templates/groups/mygroups.html
{% extends 'groups/group_base.html' %}
{% block group_content %}
<h1>My Groups</h1>
<div class="container">
  <ul>
    {% for g in my_groups %}
    {% if g.user == user %}
  <h2><li><a href="{% url 'groups:single' slug=g.group.slug %}">{{g.group}}</a></li></h2>
    {% endif %}
    {% endfor %}
  </ul>
</div>
{% endblock %}
<li>